### ISSUE TITLE
Support for Spanish speech

### ISSUE THREAD

**Issue by numeropi** [Kaljurand/K6nele-service#10]
Hi, i like this app bcs ti automagically connects with the speech-to-text button that keyboards has in Android... we are happy non-users of Google services... 

I'd like to see also Spanish support in this app... maybe you can get inspired by the API services used by 

https://github.com/Stypox/dicio-android

which renders the speech quite well. 

Thanks

**Comment by Kaljurand** [comment]
Kõnele-service is only a front-end for servers that run the  https://github.com/alumae/kaldi-gstreamer-server software. So support for Spanish should be added on the server side, i.e. this is out-of-scope for Kõnele-service.

This would also be out-of-scope for the Kõnele project (which is just a UI for services like Kõnele-service). Since Dicio uses Vosk, look into, e.g.

- https://github.com/alphacep/vosk-android-service
- https://github.com/ewheelerinc/LocalSTT

These might work with the Kõnele (or another Android) IME and/or support Spanish.
