### ISSUE TITLE
Difference with the past kõnele app?

### ISSUE THREAD

**Issue by Oymate** [Kaljurand/K6nele-service#2]
What's the difference?

**Comment by Kaljurand** [comment]
Kõnele-service is a subset of (the current) Kõnele: while Kõnele contains the UI (e.g. the virtual keyboard) and 2 services, the Kõnele-service contains just one of the services. The original motivation for extracting the service into a separate app, was that otherwise the service cannot be used on Android 11, for reasons still unknown to me (see more in https://github.com/Kaljurand/K6nele/issues/82). However, even if this limitation gets resolved somehow, having services in separate apps offers more flexibility.
